# Generated by Django 4.1.7 on 2023-03-31 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="admins",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="admins",
            field=models.ManyToManyField(
                related_name="admin_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="member_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
