# Generated by Django 4.1.7 on 2023-04-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_team_admins_remove_team_members_team_admins_and_more"),
        ("inbox", "0005_messages_delete_broadcasts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="teams",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.team",
            ),
        ),
    ]
