# Generated by Django 4.1.7 on 2023-03-31 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("actions", "0002_resource1_delete_resource"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="resource1",
            new_name="resource",
        ),
    ]
