# Generated by Django 4.1.7 on 2023-03-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0003_rename_resource1_resource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="resource",
            table=None,
        ),
    ]
