# Generated by Django 4.1.7 on 2023-04-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0004_resources"),
    ]

    operations = [
        migrations.DeleteModel(
            name="resource2",
        ),
    ]
