# Generated by Django 4.1.7 on 2023-03-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0005_resource1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource1",
            options={"managed": True, "verbose_name": "resource1"},
        ),
        migrations.AlterModelTable(
            name="resource1",
            table="resource1",
        ),
    ]
