# Generated by Django 4.1.7 on 2023-03-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0006_alter_resource1_options_alter_resource1_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="resource",
        ),
    ]
