# Generated by Django 4.1.7 on 2023-03-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0008_rename_resource1_resource_alter_resource_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="description",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="name",
        ),
    ]
